# End your baseURL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL = "https://irenechen.net/"

languageCode = "en-us"
title = "Irene Chen"
theme = "one"
googleAnalytics = "UA-72495497-1"

# Chroma Syntax Highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
    navigation = ["blog.md", "talks.md", "resources.md", "reading-list.md"]

[permalinks]
    posts = "/:year/:month/:title/"
